### ISSUE TITLE
Can't execute more than one command with ExecuteSystemCommand

### ISSUE THREAD

**Issue by dsomar** [GoyaPtyLtd/BaseElements-Plugin#102]
Am I missing something - but I can't run more than one command using BE_ExecuteSystemCommand...

If I want to change directories then return the working directory, this doesn't work as I only get a blank result:
BE_ExecuteSystemCommand("
 cd Applications
ls
")

**Comment by petrowsky** [comment]
Within the shell environment you have to end your command with a semi-colon. Try this.

BE_ExecuteSystemCommand("cd Applications; ls")

And typically, when composing a shell script you use absolute paths.

```
BE_ExecuteSystemCommand("/usr/bin/cd /Applications; /bin/ls")
```

**Comment by dsomar** [comment]
Matt,

Thank you!  I thought the line return was the end of the command.

Cheers,
Denis

**Comment by dsomar** [comment]
With that said, are we able to run Ruby from a shell command using the
plugin?

Doing this works:
cd Users/me/Desktop; ls

Trying to run the ruby file on my desktop does not:
cd Users/me/Desktop; ruby test.rb

and returns a question mark.

Any ideas are REALLY appreciated.

Thanks again,
Denis

**Comment by petrowsky** [comment]
Running shell scripts is a matter of permissions. Since the plugin is running under the FileMaker app, which is running under your user account you would need to make sure the script is executable. Which would most likely be chmod 755 on test.rb.

Again, you should also use absolute paths. Such as /usr/bin/ruby instead of just ruby. It's possible to have multiple installs of ruby and a user can modify their profile so that a different version of ruby (other than the one installed by Apple) is used. From say /usr/local/bin/

**Comment by nickorr** [comment]
And ... the BE_ExecuteSystemCommand runs under the sh shell on Mac, not the bash shell like the Terminal app does.  There can be differences in commands between the two as well.

"cd Users/me/Desktop" may not take you where you expect, use "cd /Users/me/Desktop" instead.  Absolute paths are required.

Cheers,
Nick
