### ISSUE TITLE
BE_copyfile issue with Mac path

### ISSUE THREAD

**Issue by rwu2359** [GoyaPtyLtd/BaseElements-Plugin#110]
If I use the full path
/Volumes/Macintosh HD/Users/john/Documents/RMP_FM/

then BE_CopyFile appears to fail.

Using
/Users/john/Documents/RMP_FM/
seems to work.

Is this by design? as the function I am using to select the file gives me the full path..

**Comment by nickorr** [comment]
John,

Can you give me exact examples?  The copy function requires a path to the destination file, not just the destination folder.

Cheers,
Nick

**Comment by DanShockley** [comment]
Just a side note: your example ( /Volumes/Macintosh HD/Users/john/Documents/RMP_FM/ ) is not the actual "full path" in this case, but it looks like it should work, since the boot disk name in /Volumes should be a symbolic link to the actual mount point ( / ), which means the true "full path" is /Users/john/Documents/RMP_FM/

**Comment by nickorr** [comment]
Dan,

Thanks for that, I had never looked at the details of actual path vs the /Volumes path.

Cheers,
Nick
