### ISSUE TITLE
BE_ConvertContainer Issue

### ISSUE THREAD

**Issue by PudgyPlatypus** [GoyaPtyLtd/BaseElements-Plugin#115]
Hey there Goya,

Thanks for an awesome plugin! I had a quick issue I found that stumped me.

When using the newer function ConvertContainer, it rotates jpg images 90 degrees (usually only if the image is portrait). I don't think it is the ImportFile part of the script, but I'm not totally sure. I wrote a quick example if you want to see it real quick with an image I know it happens to.

(I'm on Version 3.1.2)

Thanks again!

Nick
[ExampleIssue_BaseElements.fmp12.zip](https://github.com/GoyaPtyLtd/BaseElements-Plugin/files/97890/ExampleIssue_BaseElements.fmp12.zip)

**Comment by nickorr** [comment]
Thanks, I can confirm the issue.  We'll look into it and see what we can do.

Cheers,
Nick

**Comment by nickorr** [comment]
This may be a combination of FileMaker bug and this particular image.  The image metadata has this in it for "orientation" :

"6 (Rotated 90 CCW)"

which means it's stored one way but should be displayed another.  So take the "bad" image from your test file, and export to disk and open it, and it's fine.  So the convert isn't rotating it.

But the insert that we can do via the plugin doesn't recognise the rotation in the orientation meta data, so it then creates it's own preview which isn't correct.

There's nothing we can do about this in the plugin, or the API.  The issue is a limitation in the API or a bug depending on how you see it.

Sorry I can't be of more help, but let us know if you submit a bug report for it.

Cheers,
Nick
