### ISSUE TITLE
BE_SMTPSend encoding

### ISSUE THREAD

**Issue by dkiriakopoulos** [GoyaPtyLtd/BaseElements-Plugin#165]
Hi,

when I send an email, there is a problem with the encoding of letters such as é, à in the Subject. In the body of the message, it's perfect but in the title there is an encoding problem (at least in Outlook).

Thank you,

**Comment by nickorr** [comment]
Dennis,

I'll close this issue here, but feel free to send something to the support@freefilemakerplugin.com if you have further issues.

For the issue, try this :

BE_SMTP_Send ( "me@example.com" ; "you@ example.com" ; "=?utf-8?B?" & Base64Encode ( "Test 2018 für" ) & "?=" ; "Test 2018 für" ; "" ; "" ; "" ; "" ; "" )

Cheers,
Nick
