### ISSUE TITLE
Version >4.0.4 crash on exit

### ISSUE THREAD

**Issue by abross86** [GoyaPtyLtd/BaseElements-Plugin#179]
FileMaker 17.0.7, OSX 10.12.6
When closing FileMaker with BE installed (v4.0.5 and greater), FileMaker crashes. This happens after using a BE function and then exiting. If a BE function is never called, there is no crash. I've included the crash report below. This does not happen in v4.0.4 and older.

[Crash report](https://pastebin.com/bd9c9YS8)

I'm not sure if this is relevant, but I have found that when I also have a 360works plugin installed (email), instead of crashing, FileMaker will just hang on exit and will need to be force quit. This only happens with the combination of the 2 plugins.

**Comment by nickorr** [comment]
abross86,

This plugin crash has no mention of any plugins being installed, BaseElements or otherwise.  I'd suggest this is a native FileMaker crash, not plugin related at all.

Also the crashed thread is very sparse with almost no detail included.

If you have a different crash with BE installed, I'd be happy to look at it.

Cheers,
Nick

**Comment by abross86** [comment]
BaseElements was definitely installed during this crash, along with 360works. I can recreate it every time I quit FileMaker. I'm not sure why the crash logs don't show any plugin information, maybe the crash happens immediately after they are unloaded from memory. Removing the BaseElements plugin, or downgrading to 4.0.4 immediately fixes the problem. The crash also does not occur if I do not call any BaseElements functions before quitting FileMaker.

**Comment by nickorr** [comment]
There's not much I can tell you though, if the report doesn't even mention BE being installed, and if there's a similar issue with another plugin.

I'm guessing there's something either amiss with your system or the specific FileMaker install.

I've got the same setup, and can run BE 4.1.2 under FMPA 17 with no issues and no crashes.

If the log showed an issue with BE in the crashed thread, then that might point to an answer but otherwise I can't help you much, sorry.

Cheers,
Nick

**Comment by abross86** [comment]
Sure, here is the crash report from the stock install. I still don't see any sign of the plugin in the report, but could be worth a look.
https://pastebin.com/TeXPisBY

**Comment by nickorr** [comment]
Yep, I can confirm this does cause a crash, and does seem to only happen with 4.1.2 and only on Mac OS 10.12.  We'll investigate and let you know.

Cheers,
Nick

**Comment by nickorr** [comment]
Followup on this : the minimum Mac OS version for 4.1 and later is now 10.13 and that's what it's been built for.  Unfortunately this wasn't in the docs, so I'll have to update them to make it clearer.

So it's built against 10.13 as the minimum, sorry :(

Cheers,
Nick

**Comment by nickorr** [comment]
Also, 4.0.x is still supported on 10.12, so there is that option.

Cheers,
Nick

**Comment by abross86** [comment]
Thanks for looking into this for me! I'll stick to 4.0.4 until we can move to 10.13
