### ISSUE TITLE
BE_ExecuteSystemCommand hang (beachball)

### ISSUE THREAD

**Issue by xenophon61** [GoyaPtyLtd/BaseElements-Plugin#192]
Hi. Thanks for a great resource!

Perplexing issue with the BE_ExecuteSystemCommand, on FMP18 (Catalina 10.15.7):

- the command BE_ExecuteSystemCommand("caffeinate";0) hangs Filemaker (beachball) until the caffeinate process is killed
- this did not occur on 4.1.2, but only from 4.1.3 onwards
- a workaround is to try BE_ExecuteSystemCommand("caffeinate &";0) which works, amazingly
- this is unique to /usr/bin/caffeinate, perhaps

On a related note, I could not install 4.1.4 on Catalina, because the Security pref pane will not respond to my clicking "Allow always".

Once again, thanks!!!

With greetings from Athens,

Xen

**Comment by nickorr** [comment]
Xen,

Yes, you're right, it should return immediately.  I'm guessing there's something specific about that command that causes that issue.

We'll look into it.

Cheers,
Nick

**Comment by kvnvandenbrande** [comment]
Having the same issue here. The BE_ExecuteSystemCommand with parameter 0 does not return to FileMaker, only after the process is finished

**Comment by nickorr** [comment]
Some followups on this one :

First: caffeinate is unusual but the behaviour will occur with other process with the current implementation.

Second: The changes in 4.1.3 are a modified version of the previous (2/3.x) implementation which does not address the changes to the specification/documented behaviour in 4.x. Notably, with a 0 second timeout, the current implementation does not return immediately leaving the command running, it terminates the command (or tries to).  Starting a command that you just then try to quit kind of defeats the purpose of the command in the first place.

Letting the user launch multiple processes, which never complete and can't be properly closed by the plugin is a cause of issues, not really memory, but more file descriptors and other things, but effectively a leak.

It would be possible to modify the code match the documented behaviour but this would re-introduce a memory leak, which is why we changed behaviour in the first place. 

We can change the docs and effectively remove the 0 option, and force the user to do a timeout, which forces the closing of the command that you launched.  

We can change the Mac behaviour to launch a shell first, which seems to negate some of the issues, but could cause other issues.

Is there a use case for this that requires it not to timeout, that can't be solved via changing the command that you're using?

**Comment by kvnvandenbrande** [comment]
Well if you want to execute a program where you have no idea of the time it will take, the 0 option is required here. For example in the FMDataMigration FileMaker file ( https://www.myfmbutler.com/en/products/fmdatamigration/13 ) I make use of the 0 option. Without this option I have to specify an extremely long timeout so I can make sure the process will finish before the timeout. Besides that I can not inform the user anymore where the long process is in it's tasks (which I do with another shell command)

**Comment by nickorr** [comment]
But isn't that my question : should a database be launching a potentially unlimited number of processes that may never end?  When it all comes crashing down, then people blame the plugin for not managing memory properly ( which is exactly why we made a change that is causing this issue ).

That's my question : if in this situation it's required or assumed that you don't know the end time, how else could we or you manage it?  

Assuming that you can also do the same thing on a server schedule that runs once a minute?

**Comment by kvnvandenbrande** [comment]
Well we all know that system commands are extremely powerful and should be used with caution. To me, it's up to the user to make sure he handles everything correct. 

With that timeout option set to 0 we have the possibility to perform a taks asynchronous which is to me a huge benefit. The developer should make sure everything is handled in the backend. The FileMaker script step 'perform script on server', the option 'wait for completion' is crucial here. The user must be able to decide himself if he wants to wait or not. Off course we can't compare this to system commands but it's just the idea behind it.

I reference here the MBS plugin ( https://www.mbsplugins.eu/ShellExecute.shtml ) which make use of separate commands to release the executed function shell function. Here also the developer has the control. If he does not release the shell commands properly issues will arise. 

Isn't it possible that the ExecuteSystemCommand with option 0 return maybe the process ID and that the developer is after in control (with a different command) to release the memory?

**Comment by nickorr** [comment]
All,

We've got a new build.  This switches to a different engine that shouldn't have the same issues as before.  Plus to resolve the issue of multiple commands not working in the alternate engine, this adds a new option to the command, executeUsingShell : 

BE_ExecuteSystemCommand ( command { ; timeout ; executeUsingShell } )

This defaults to True, meaning that the plugin is going to wrap your command in "cmd /c " on windows and “/bin/sh -c “ on Mac.

This should resolve the issue of multiple commands not working, but it can also be removed for compatibility, if required.  Test versions : 

https://dl.dropbox.com/s/g3wz4eq27deuekc/BaseElements.fmplugin.zip
https://dl.dropbox.com/s/0iiramiebnjujkd/BaseElements.fmx64.zip

Let me know how you go.

Cheers,
Nick
