### ISSUE TITLE
BE_FileListFolder returns "?" when number of objects found is too large ?

### ISSUE THREAD

**Issue by jfri34070** [GoyaPtyLtd/BaseElements-Plugin#198]
I use BE_FileListFolder to check if a folder is already existing in a master folder :
When i try to load all the folders using BE_FileListFolder ( $MasterFolder ; BE_FileTypeFolder ; True), the function returns "?" when the number of folders founds is too large (between 4 000 to 5 000 in my case)

**Comment by nickorr** [comment]
Ok, thanks.  Can you let me know exact version numbers of the plugin, the OS, FileMaker and what BE_GetLastError is.

**Comment by jfri34070** [comment]
Thanks for the reply, below the informations:
Plugin Version : 4.1.4
OS : Microsoft Windows [version 10.0.19042.1052]
Filemaker : 18.0.3.217
BE_GetLastError : 5

**Comment by nickorr** [comment]
Error 5 is likely to be an access issue, not a size of the list.

https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-

Which means you've ended up at a folder you don't have access to.  At that point the library stops returning data.

The only way around this is to use a looping script that checks individual folders and appends the file list each time.

**Comment by jfri34070** [comment]
I have already coded the workaround with a recursive script based on the BE_FileListFolder function.

I was surprised by the fact that the error was coming from an access issue. 
So i have changed the rights on the folders and i have the same issue (functions returns ?) but with error code -1

**Comment by nickorr** [comment]
Ok, for the -1 error, that's different and could be internal.

Can you tell me the exact function calls you're using that get that path?

**Comment by jfri34070** [comment]
Hereunder part of the script :
Set Variable [$path;"\\\Srv\Shared"]
or
Set Variable [$path;"S:"]

Set Variable [$LstFolders;BE_FileListFolder($path;BE_FileTypeFolder;True]

**Comment by nickorr** [comment]
Sorry, you said you were doing a looping script : if you're doing the True for the includeSubdirBoolean option, then it's not looping to test individual folders.  

I assume with that set to False, it works, and some point down the folder hierarchy it fails on one specific folder, but you'd need to find out which folder that was.

**Comment by jfri34070** [comment]
I have said that i have done a recursive script as a workaround (with False for the includeSubdirBoolean) because with True for the includeSubdirBoolean i have the error.

The "DIR" command doesen't return any error (lenght of dir, ...).
What kind of fail could happen on a specific folder ?

**Comment by nickorr** [comment]
Yes, but the error isn't on the root folder, it's later on at some point during the recursion.   It happens on one specific folder, so my question about looping and the error was : do you find an error later, on a deep sub folder or file?  If so, what is that exact folder path and what is the error?

**Comment by jfri34070** [comment]
I have made several trials and finally found something : it seems to come from the lenght of the path.
The folders are created by people of our organisation and they use a network mapping with a letter to acces the folders: something like O:\MyFolder\folder1\folder2\...
But when i use your function i use the UNC path like "\\SRV\Shared\Department\MyFolder\folder1\folder2\..." which increase the length of the path.
When i use the function with the mapped drive letter, i don't have an error but when i use the UNC path, in some deep folders i have an error.

**Comment by nickorr** [comment]
Ok, can you tell me an exact path that has an error?  Perhaps there's a character limit.

**Comment by jfri34070** [comment]
The full paths with errors are (Last Names has been changed) for example : 
"\\SRV-N1\Partages\Orthophedie\flavie.daudiy\Traite\0-REUNION\0-ESSAYAGE NON REALISE REUNION\GAUTTEUUE Carole Marie 04.09.2019 LE PORT (ORDO A LA LIV)RENOUVELLEMENT INJUSTIFIE MEME MESURE QU'EN AVRIL NE PAS DELIVRER !!!!!"
or 
"\\SRV-N1\Partages\Orthophedie\flavie.daudiy\Traite\0-REUNION\2-TEST SG REUNION\ESSAYAGE VALIDE\DAUIESINE Marie Suzie 04.07.2019 LE PORT\NESONWIMME Marie Claudette 04.07.2019 LE PORT"

**Comment by nickorr** [comment]
I can't see anything in the path that would cause issues with characters, so my guess is either that it's a permissions thing, or a length issue.

Is that a folder, or the path to a document?  Because I can create that length folder just fine on windows :

BE_FolderCreate ( "c:\SRV-N1\Partages\Orthophedie\flavie.daudiy\Traite\0-REUNION\0-ESSAYAGE NON REALISE REUNION\GAUTTEUUE Carole Marie 04.09.2019 LE PORT (ORDO A LA LIV)RENOUVELLEMENT INJUSTIFIE MEME MESURE QU'EN AVRIL NE PAS DELIVRER !!!!!"
 )

And BE_FileExists on the path works.  But if I add a sub folder of more than a few characters, it fails : 

BE_FolderCreate ( "c:\SRV-N1\Partages\Orthophedie\flavie.daudiy\Traite\0-REUNION\0-ESSAYAGE NON REALISE REUNION\GAUTTEUUE Carole Marie 04.09.2019 LE PORT (ORDO A LA LIV)RENOUVELLEMENT INJUSTIFIE MEME MESURE QU'EN AVRIL NE PAS DELIVRER !!!!!\twenty1234chars12345thirty"
 )

Create returns 0 and BE_GetLastError returns 206.  If there were files in that folder with long names, you may get this issue.

Otherwise I'd suggest it's permissions based.

**Comment by jfri34070** [comment]
I agree (see my previous comment), it 's not a permissions error , it is due to the lenght of the path. But, getting only a -1 error with BE_GetLastError is not very helpfull. Thanks for the support and long file for all the BE functons !!!

**Comment by nickorr** [comment]
We were thinking about the -1 issue and realised this is one of our catch all error codes when a library throws an error that it doesn't deal with.  So this code :

	} catch ( BEPlugin_Exception& e ) {
		error = e.code();
	} catch ( bad_alloc& /* e */ ) {
		error = kLowMemoryError;
	} catch ( exception& /* e */ ) {
		error = kErrorUnknown;
	}

Basically says if you give us an error, return that, we run out of memory, return that, otherwise on any other "exception", return kErrorUnknown which is -1.

So the OS or the library has died or faulted in a way that we don't get any useful info from it, so we just bail out with -1.

So your best bet is to handle this in your loops and keep track of these and alert the end user :)

**Comment by jfri34070** [comment]
Thanks for your suggestion on the loops, it was done since our last reply ;-)
