### ISSUE TITLE
BE_JSON_Error_Description should not set BE_GetLastError

### ISSUE THREAD

**Issue by dansmith65** [GoyaPtyLtd/BaseElements-Plugin#83]
This is the same basic issue as #26 . Basically, I'm never going to care if `BE_JSON_Error_Description` itself encounters an internal error, so this function shouldn't modify the value that `BE_GetLastError` returns. I think the following test case should return 1.

```
BE_JSONPath ( "invalid json" ; "$" ) = "?"
and Not IsEmpty ( BE_JSON_Error_Description )
and BE_GetLastError <> 0
```

**Comment by nickorr** [comment]
Dan,

This one is tricky.  Technically you should call BE_GetLastError first to see if there’s any errors, that will tell you about every error, not just a JSON specific one ( i.e. low memory faults wouldn’t have a JSON description ).

But it’s also possible to have BE_JSON_Error_Description throw an error ( low memory ) which would mean that it had issues and that would cause it not to work, or to return the value of the previously cached result.

But we’ve adjusted the code so that we don’t trap any errors in the BE_JSON_Error_Description function so that won’t alter the BE_GetLastError result.  This will be in the next build.

Cheers,
Nick

**Comment by dansmith65** [comment]
Thanks!

Yes, I see how it's a bit of a tricky scenario. I was only thinking of production code, where I won't ever test for an error after `BE_JSON_Error_Description`. But now I realize that if I was debugging an issue where `BE_JSON_Error_Description` seemed to be returning invalid results, I may want `BE_GetLastError ` to work how it does right now.

Given that we can only have one or the other, I'm glad you made the suggested change, so thanks again.

**Comment by dansmith65** [comment]
I'm not sure if you want to re-visit this again or not, but I've got 3.0.0 installed and `BE_JSON_Error_Description` still re-set's the value returned by `BE_GetLastError` to 0, so this:

```
List (
	BE_JSONPath ( "{bad"; "" ) ;
	BE_GetLastError ;
	BE_JSON_Error_Description ;
	BE_GetLastError
)
```

currently returns this:

```
?
1
Error: string or '}' expected near 'bad' Line: 1 Column: 4 Position: 4
0
```

**Comment by nickorr** [comment]
Dan,

Yep, this will be fixed in the next build.

Cheers,
Nick
