### ISSUE TITLE
BE_WriteTextToFile returns ? with other problems then invalid path

### ISSUE THREAD

**Issue by PeterWagemans** [GoyaPtyLtd/BaseElements-Plugin#98]
I have some text here in UTF-8, nothing fancy, just some addresses with accents like  "L’ALLEUD"
The function returns ? when used in combination ( and only in combination ) with BE_SetTextEncoding ( "ISO-8859-1" ), and I pinned it down to the string mentioned above.

The documentation seems not consistent with the error: 
"Result : 0 on success, ? for an invalid path and a OS error code on failures."

Putting EvaluationError around the BE_WriteTextToFile function call reveals that the actual error code = -1. Since it is not mapped to a FileMaker error, I guess the plug-in ran into some unexpected problem.

A simple way to test it in the data viewer:
EvaluationError ( BE_WriteTextToFile ( "/Users/peter/Desktop/text.txt" ; "L’ALLEUD" ) )

versus

BE_SetTextEncoding ( "ISO-8859-1" ) & EvaluationError ( BE_WriteTextToFile ( "/Users/peter/Desktop/text.txt" ; "L’ALLEUD" ) )

Can you confirm this? Or am I doing something wrong?

**Comment by nickorr** [comment]
Peter,

A couple of things.  The evaluation error doesn’t work that way, it won’t give you the response you’re expecting.  It’s trying to evaluate the result of the BE function call, which is ? which doesn’t evaluate to anything.

IF you get ? from the plugin, it means there’s an error, check the BE_GetLastError function for the actual error code.

Cheers,
Nick

**Comment by PeterWagemans** [comment]
Morning Nick. I'm not doing an Evaluate()function  but an EvaluationError() function which in this case returns exactly the same error: -1.
I think the BE_LastError function was designed to obtain the error later, and I can see in the source code that MapError() confirms that.
But in the mean time, I've seen that other libiconv conversions work, just not this one and a few others. The error -1 is not relevant though.
Maybe converting UTF-8 to ISO-8859-1 or CP1252 ( which gets me a little further, but get stuck on czech character )  just isn't possible, but it's kinda frustrating not getting any meaningful error back from the libiconv library.. It would help if google - or you - could give me a link where I can read more information about libiconv error -1.

**Comment by nickorr** [comment]
Peter,

Do this instead :

BE_SetTextEncoding ( "ISO-8859-1" ) & ¶ & 
BE_WriteTextToFile ( BE_SaveFileDialog ( "" ) ; "L’ALLEUD" ) & ¶ & 
BE_GetLastError

This gives you the real error code, which is 92.  I can't find anything about it on the web, but there's an easier way to test.  Copy that text into a real text editing app like BBEdit and try to save it as ISO Latin 1.  It will give you a warning that there is a character in there that can't be mapped to that character set, and you should instead save as UTF8.

So that's your answer, it can't be represented as your choice of encoded format.  The -1 error from EvaluationError is a red herring here, and unrelated to the error from the file operation, which is what you need the BE_GetLastError function.

Cheers,
Nick

**Comment by PeterWagemans** [comment]
At the risk of appearing to want to have the last word here, even after you meaningfully closed this:

Set Variable [$r; Value:MBS("Text.WriteTextFile"; $fileContents ; $path; "windows")]

Worked from the first time I tried it. I guess I'm forced here to evangelise BaseElements a bit less.

**Comment by nickorr** [comment]
Peter,

Wi don't know what the "windows" encoding format actually is, can you send me a copy of the output file? ( nick@goya.com.au )

Also did you check that the actual file has the right content?

Cheers,
Nick

**Comment by nickorr** [comment]
Peter,

For what it's worth, I tried your text using the MBS plugin on the mac and got an OK back from the plugin, but it wrote this into the file :

LíALLEUD

and the output file was in "Western ( Mac OS Roman)" encoding format.  So it still seems to me like an encoding issue.

I'm happy to help if I can, but I don't think you can write that text to a file, in something other than utf-8.

Cheers,
Nick

**Comment by PeterWagemans** [comment]
I've send to you an example file using regular mail, so you can compare the 2 methods. I really hope I'm doing this the wrong way.

**Comment by nickorr** [comment]
Peter,

I've sent you a note off list. You're not doing anything wrong, it's just encoding.  The MBS plugin reports that it's OK, but isn't actually writing your content properly, and is failing to report that it's modifying the output to suit the encoding choice.

You're stuck with either using UTF8 or having some characters not be accurate in the output.

Cheers,
Nick

**Comment by PeterWagemans** [comment]
Hi Nick,
Thanks for taking the time to look at this. Some UTF-8 character do not have an equivalent in other character encodings. So the possible outcome is a bit like choosing between Cholera or The Plague. The BaseElements plug-in is correct to report the error, but the MB plug-in just skips the character, and that makes it useable. Maybe the BE_WriteTextToFile function should additionally continue to write the rest of the buffer apart from only reporting the error instead of not writing the rest of the buffer as it does now. Working around the issue with the BE_WriteTextToFile function would require to write a buffer of... 1 character in order to generate a useable file.

The file is required for a bookkeeping application that does not understand UTF-8. The customer will accept the loss of characters as acceptable.
Cheers and thanks for picking this up again. -- peter

**Comment by nickorr** [comment]
Peter,

Perhaps I have a different approach to Christian with the MBS plugin, but I don’t think that it’s good to write out to disk output that doesn’t match the input.  I think it’s a bug and should throw an error, and I wouldn’t change the behaviour.

For example, there be other people using that function that require 100% accuracy and assume because there’s no error that the plugin is doing the right thing.

In your case, I think you’d be better off converting it from utf8 to the alternate encoding first, and then writing to disk.  There isn’t anything in the BE plugin to convert encodings, but there is in MBS :

MBS( "Text.ConvertEncoding"; "Hello world √  "; "Windows” )

Christian also mentioned that he thinks it’s fine to write content that is different, in his words :

> it matches the character to a close match to preserve as much as possible.

Which I disagree with.  But there you go, that’s the benefit of multiple choices for this.

Cheers,
Nick
